version: "3.3"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  web:
    container_name: django_task_manager
    build: .
    command: bash -c "python manage.py migrate --noinput && 
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY='your secret here there'
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

