# Generated by Django 4.0.1 on 2022-01-04 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT,
                    related_name='%(app_label)s_%(class)s_author',
                    to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT,
                    related_name='%(app_label)s_%(class)s_executor',
                    to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(to='task_manager.Label')),
                ('status', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT,
                    to='task_manager.status')),
            ],
        ),
    ]
