# Generated by Django 4.0.1 on 2022-01-09 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_manager', '0002_alter_task_options_alter_task_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTaskIntermediate',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('label_link', models.ForeignKey(
                    on_delete=django.db.models.deletion.RESTRICT,
                    to='task_manager.label')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='executor',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Исполнитель'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='labels',
        ),
        migrations.AddField(
                model_name='task',
                name='labels',
                field=models.ManyToManyField(
                    through='task_manager.LabelTaskIntermediate',
                    to='task_manager.Label'),
             ),
        migrations.AddField(
            model_name='labeltaskintermediate',
            name='task_link',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='task_manager.task'),
        ),
    ]
