# Generated by Django 4.0.1 on 2022-01-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager',
         '0003_labeltaskintermediate_alter_task_executor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeltaskintermediate',
            name='label_link',
        ),
        migrations.RemoveField(
            model_name='labeltaskintermediate',
            name='task_link',
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
        migrations.RemoveField(
            model_name='task',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='LabelTaskIntermediate',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
