version: "3.3"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_tm:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  web:
    container_name: django_task_manager
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: docker/start.sh
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY='your secret here there'
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

volumes:
  postgres_tm:
