# Generated by Django 4.0.1 on 2022-01-17 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statuses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTaskIntermediate',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('label_link',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.RESTRICT,
                     to='labels.label')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=150,
                                          unique=True,
                                          verbose_name='Наименование задачи')),
                ('description', models.TextField(
                    verbose_name='Описание задачи')),
                ('creation_date',
                 models.DateTimeField(auto_now_add=True,
                                      verbose_name='Дата создания')),
                ('author',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.RESTRICT,
                     related_name='author',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Автор')),
                ('executor',
                 models.ForeignKey(
                     null=True,
                     on_delete=django.db.models.deletion.RESTRICT,
                     related_name='executor',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Исполнитель')),
                ('labels',
                 models.ManyToManyField(
                     through='tasks.LabelTaskIntermediate',
                     to='labels.Label')),
                ('status',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.RESTRICT,
                     to='statuses.status',
                     verbose_name='Текущий статус')),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задачи',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='labeltaskintermediate',
            name='task_link',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='tasks.task'),
        ),
    ]
